/*
 * build.gradle
 * Copyright 2018 Radiologics, Inc
 * Developer: James Ransford
 */
 
 
import org.gradle.internal.jvm.Jvm

group 'com.radiologics'
version '1.2.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'maven-publish'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'net.linguica.maven-settings'

buildscript {
    ext {
        vXnat     = "1.10.1-SNAPSHOT"
    }
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
        mavenLocal()
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
        maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:1.1.7"
        classpath "net.linguica.gradle:maven-settings-plugin:0.5"           
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenLocal()
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
    mavenCentral()
}

dependencyManagement.imports {
    mavenBom "org.nrg:parent:${vXnat}"
}

dependencies {
    annotationProcessor "org.nrg:framework"

    implementation ("org.nrg.xnat:web"){
        exclude group: '*'
    }
    
    implementation ("org.nrg.xdat:core"){
        exclude group: '*'
    }

    // xnat-data-models merged into xnat-web in monorepo 1.10
    implementation "org.nrg:framework"

    implementation "org.apache.commons:commons-configuration2"
    implementation "org.apache.commons:commons-math"
    implementation "org.apache.commons:commons-text"

    implementation "com.noelios.restlet:com.noelios.restlet"
    implementation "com.noelios.restlet:com.noelios.restlet.ext.servlet"
    implementation "org.restlet:org.restlet"

    implementation group: 'org.apache.turbine', name: 'turbine', version: '4.0-M1'
    implementation group: 'org.apache.velocity', name: 'velocity', version: '1.7'
    compileOnly "javax.servlet:javax.servlet-api"
}

idea {
    module {
        inheritOutputDirs = false
        outputDir = compileJava.destinationDirectory.asFile.get()
        testOutputDir = compileTestJava.destinationDirectory.asFile.get()
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories{ 
        maven {
            url "https://nrgxnat.jfrog.io/nrgxnat/libs-${project.version.endsWith("-SNAPSHOT") ? "snapshot" : "release"}"
            // The value for name must match <id> in ~/.m2/settings.xml
            name = "XNAT_Artifactory"        
        }
    }
}
